### ISSUE TITLE
Option to clear panels

### ISSUE THREAD

**Issue by andrewhubbs** [spect88/backbone-devtools#1]
The panels tend to get over loaded with content so that loading becomes very slow or unresponsive (especially the events panel).

An option to clear would go a long way toward mitigating the problem.

I don't mind taking a stab at adding this if you point me in the right direction.

**Comment by danmactough** [comment]
@andrewhubbs Oh thank god it's not just me. +1

**Comment by spect88** [comment]
@andrewhubbs Sounds reasonable, I'll add a button for clearing the logs. :)

I'm going to fix responsiveness by making log polling interval-based instead of event-based as it is right now. The code should be cleaner as well.

**Comment by spect88** [comment]
@andrewhubbs I've added the button just now, so I'm closing this issue.

**Comment by andrewhubbs** [comment]
Thanks Tomasz. I'll check it out.

On Mon, Apr 22, 2013 at 6:01 PM, Tomasz Szczęśniak-Szlagowski <
notifications@github.com> wrote:

> @andrewhubbs https://github.com/andrewhubbs I've added the button just
> now, so I'm closing this issue.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spect88/backbone-devtools/issues/1#issuecomment-16833449
> .

## 

Cheers

Andrew Hubbs
andrew@hub.bs
@andrewhubbs https://twitter.com/#!/andrewhubbs
