### ISSUE TITLE
How to get backbone instance variables

### ISSUE THREAD

**Issue by aakkashshah** [spect88/backbone-devtools#10]
I need to debug the instance variables, how do i find the names of instance variables on the backbone panel in console?

more on this at http://stackoverflow.com/questions/16890437/get-backbone-collection-model-instances-from-a-live-app

**Comment by spect88** [comment]
If I understand correctly what you're trying to do, the answer is: you can't.

You can see constructor function names if they're named (usually the case for apps written in CoffeeScript), but there's no easy way to find out what variables hold reference to that object's instances.

You could inspect a part of page that you believe is rendered by a specific view, then use $view in console. If that view holds references to any collections or models, you'll probably easily reach it (eg. $view.model).
